/**
 * Cardápio China Express — categorias, produtos, preços e dados fiscais.
 * Gerado por scripts/gerar-china-express-catalogo.py — não editar manualmente.
 */

export interface ProdutoChinaExpressSeed {
  nome: string
  precoCentavos: number
  fiscalNcm: string
  fiscalCest: string | null
  fiscalCfop: string
  fiscalIcmsCsosn: string
  fiscalPisCst: string
  fiscalCofinsCst: string
}

export interface CategoriaChinaExpressSeed {
  nome: string
  produtos: ProdutoChinaExpressSeed[]
}

export const CHAVE_METADATA_SEED_CHINA_EXPRESS = 'seed_china_express_v1'

export const CATEGORIAS_CHINA_EXPRESS: CategoriaChinaExpressSeed[] = [
  {
    nome: 'Bebidas Alcoolica',
    produtos: [
      {
        nome: 'LONG NECK BUDWEISER',
        precoCentavos: 800,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'LONG NECK HEINEKEN',
        precoCentavos: 1200,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'LONG NECK HEINEKEN ZERO',
        precoCentavos: 1200,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'HEINEKEN 600 ML',
        precoCentavos: 1700,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'AMSTEL 600 ML',
        precoCentavos: 1200,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'DEVASSA 600ML',
        precoCentavos: 1000,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'AMARULA',
        precoCentavos: 1600,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'BANANINHA',
        precoCentavos: 1200,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'CARVALHEIRA CACHACA',
        precoCentavos: 1400,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'MARFINI ROSATO',
        precoCentavos: 800,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'MALIBU',
        precoCentavos: 800,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'DOSE ABSOLUT',
        precoCentavos: 1200,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'GARRAFA ABSOLUT',
        precoCentavos: 14000,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'DOSE SMIRNOFF',
        precoCentavos: 700,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'GARRAFA SMIRNOFF',
        precoCentavos: 10000,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'DOSE TANQUERAY',
        precoCentavos: 1600,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'GARRAFA TANQUERAY',
        precoCentavos: 17000,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'DOSE BLACK E WHITE',
        precoCentavos: 800,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'LITRO BLACK E WHITE',
        precoCentavos: 8000,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'DOSE JOHNNIE RED',
        precoCentavos: 1100,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'LITRO JOHNNIE RED',
        precoCentavos: 13000,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'DOSE OLD PARR',
        precoCentavos: 1600,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'LITRO OLD PARR',
        precoCentavos: 19000,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'CASAL GARCIA',
        precoCentavos: 10000,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'PERGOLA',
        precoCentavos: 5000,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'COSECHA CABERNET SAUVIGNON',
        precoCentavos: 7000,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'CHANDON BRUT',
        precoCentavos: 12000,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'CASA PERINI ROSE',
        precoCentavos: 8000,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'DOSE GIN BOMBAY',
        precoCentavos: 1800,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'LITRO GIN BOMBAY',
        precoCentavos: 18000,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'ESPUMANTE RIO SOL',
        precoCentavos: 7000,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'CERVEJA AMSTEL ULTRA LONG NECK',
        precoCentavos: 900,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'CERVEJA PRAYA LONG NECK',
        precoCentavos: 1100,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
    ],
  },
  {
    nome: 'Drinks',
    produtos: [
      {
        nome: 'PATOS DRINK',
        precoCentavos: 2200,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'NEVADA',
        precoCentavos: 2000,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'MOSCOU MULE',
        precoCentavos: 2500,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'PINA COLADA',
        precoCentavos: 2000,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'CAIPIRINHA',
        precoCentavos: 1400,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'CAIPIFRUTA',
        precoCentavos: 1700,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'GIN TONICA',
        precoCentavos: 2500,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
    ],
  },
  {
    nome: 'Refrigerantes',
    produtos: [
      {
        nome: 'AGUA MINERAL 500',
        precoCentavos: 500,
        fiscalNcm: '22011000',
        fiscalCest: '0300200',
        fiscalCfop: '5405',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '01',
        fiscalCofinsCst: '01',
      },
      {
        nome: 'AGUA C GAS 500',
        precoCentavos: 600,
        fiscalNcm: '22011000',
        fiscalCest: '0300200',
        fiscalCfop: '5405',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'LIMONETO 500',
        precoCentavos: 900,
        fiscalNcm: '22021000',
        fiscalCest: '0301000',
        fiscalCfop: '5405',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'H2O 500',
        precoCentavos: 900,
        fiscalNcm: '22021000',
        fiscalCest: '0301000',
        fiscalCfop: '5405',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'AGUA TONICA 500',
        precoCentavos: 800,
        fiscalNcm: '22021000',
        fiscalCest: '0301000',
        fiscalCfop: '5405',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SCHWEPPES 500',
        precoCentavos: 900,
        fiscalNcm: '22021000',
        fiscalCest: '0301000',
        fiscalCfop: '5405',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RED BULL 500',
        precoCentavos: 1400,
        fiscalNcm: '22021000',
        fiscalCest: '0301000',
        fiscalCfop: '5405',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'CAFE',
        precoCentavos: 600,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'COCA COLA LATA',
        precoCentavos: 900,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'COCA COLA ZERO LATA',
        precoCentavos: 900,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'COCA COLA 1 LITRO',
        precoCentavos: 1500,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'COCA COLA 2 LITROS',
        precoCentavos: 1800,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'GUARANA LATA',
        precoCentavos: 900,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'GUARANA 1 LITRO',
        precoCentavos: 1500,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'GUARANA 2 LITROS',
        precoCentavos: 1800,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'FANTA LATA',
        precoCentavos: 900,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SODA LATA',
        precoCentavos: 900,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RED BULL ZERO',
        precoCentavos: 1600,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RED BULL TROPICAL',
        precoCentavos: 1600,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'REF BULL MELANCIA',
        precoCentavos: 1600,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
    ],
  },
  {
    nome: 'Sucos',
    produtos: [
      {
        nome: 'SUCO ACEROLA COPO',
        precoCentavos: 800,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUCO ACEROLA JARRA',
        precoCentavos: 1600,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUCO CAJA COPO',
        precoCentavos: 800,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUCO CAJA JARRA',
        precoCentavos: 1600,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUCO GOIABA COPO',
        precoCentavos: 800,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUCO GOIABA JARRA',
        precoCentavos: 1600,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUCO GRAVIOLA COPO',
        precoCentavos: 800,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUCO GRAVIOLA JARRA',
        precoCentavos: 1600,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUCO LARANJA COPO',
        precoCentavos: 800,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUCO LARANJA JARRA',
        precoCentavos: 1600,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUCO LIMAO COPO',
        precoCentavos: 800,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUCO LIMAO JARRA',
        precoCentavos: 1600,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUCO MARACUJA COPO',
        precoCentavos: 800,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUCO MARACUJA JARRA',
        precoCentavos: 1600,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUCO MORANGO COPO',
        precoCentavos: 800,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUCO MORANGO JARRA',
        precoCentavos: 1600,
        fiscalNcm: '21069090',
        fiscalCest: '1701000',
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
    ],
  },
  {
    nome: 'Diversos',
    produtos: [
      {
        nome: 'EMBALAGEM PIZZA',
        precoCentavos: 300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'EMBALAGEM',
        precoCentavos: 200,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'TAXA DE ENTREGA',
        precoCentavos: 600,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
    ],
  },
  {
    nome: 'A La Carte',
    produtos: [
      {
        nome: 'ARCO IRIS',
        precoCentavos: 300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'CARIOCA DE SALMAO',
        precoCentavos: 300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'CANAPE DE CAMARAO',
        precoCentavos: 300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'HOSSOMAKI DE CAMARAO',
        precoCentavos: 300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'CANAPE DE KANI C CAMARAO',
        precoCentavos: 300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'CANAPE DE KANI C PASTA SALMAO',
        precoCentavos: 300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'CANAPE DE KANI',
        precoCentavos: 300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'HOSSOMAKI DE SALMAO C CEBOLINHA',
        precoCentavos: 300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'CANAPE DE PEIXE BRANCO',
        precoCentavos: 300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'CANAPE DE SALMAO',
        precoCentavos: 300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'CANAPE FRITO KANI',
        precoCentavos: 300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'HOT ROLL',
        precoCentavos: 300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'CANAPE FRITO C PASTA KANI',
        precoCentavos: 300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'CANAPE FRITO DE PASTA DE SALMAO',
        precoCentavos: 300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'CANAPE FRITO DE PASTA DE KANI',
        precoCentavos: 300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'NIGUIRI DE KANI FRITO',
        precoCentavos: 300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'COCADINHA DE KANI',
        precoCentavos: 300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'NIGUIRI DE PEIXE BRANCO MACARICADO',
        precoCentavos: 300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'NIGUIRI DE KANI',
        precoCentavos: 300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'URAMAKI DE CAMARAO',
        precoCentavos: 300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'URAMAKI DE KANI',
        precoCentavos: 300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'URAMAKI DE SALMAO CREAM C E CEBOLINHA',
        precoCentavos: 300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'URAMAKI DE SALMAO',
        precoCentavos: 300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'ESTRELINHA DE PEIXE BRANCO C CEBO',
        precoCentavos: 300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'ESTRELINHA DE SALMAO',
        precoCentavos: 300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUITE RAQUEL',
        precoCentavos: 300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
    ],
  },
  {
    nome: 'Barcas',
    produtos: [
      {
        nome: 'BARCA DE MADEIRA',
        precoCentavos: 21000,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'BARCA DESCARTAVEL P',
        precoCentavos: 5500,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'BARCA DESCARTAVEL M',
        precoCentavos: 11400,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'BARCA DESCARTAVEL G',
        precoCentavos: 15800,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'BOLO DE SUSHI',
        precoCentavos: 19000,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
    ],
  },
  {
    nome: 'Bifum',
    produtos: [
      {
        nome: 'MINI BIFUM TRADICIONAL',
        precoCentavos: 2800,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'EXEC BIFUM TRADICIONAL',
        precoCentavos: 3300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'PORCAO BIFUM TRADIONAL',
        precoCentavos: 5900,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'FAMILIA BIFUM TRADICIONAL',
        precoCentavos: 9600,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'EXEC BIFUM ESPECIAL',
        precoCentavos: 4100,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'PORCAO BIFUM ESPECIAL',
        precoCentavos: 6300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'FAMILIA BIFUM ESPECIAL',
        precoCentavos: 11100,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'EXEC BIFUM SO CAMARAO',
        precoCentavos: 4600,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'PORCAO BIFUM SO CAMARAO',
        precoCentavos: 7600,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'FAMILIA BIFUM SO CAMARAO',
        precoCentavos: 13000,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
    ],
  },
  {
    nome: 'Bordas',
    produtos: [
      {
        nome: 'BORDA P CATUPIRY',
        precoCentavos: 800,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'BORDA P CHEDDAR',
        precoCentavos: 800,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'BORDA M CATUPIRY',
        precoCentavos: 1200,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'BORDA M CHEDDAR',
        precoCentavos: 1200,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'BORDA G CATUPIRY',
        precoCentavos: 1400,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'BORDA G CHEDDAR',
        precoCentavos: 1400,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
    ],
  },
  {
    nome: 'Clone De Temaki',
    produtos: [
      {
        nome: 'CLONE DE TEMAKI KANI',
        precoCentavos: 5200,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'CLONE DE TEMAKI MISTO',
        precoCentavos: 5200,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'CLONE DE TEMAKI SALMAO',
        precoCentavos: 5200,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'CLONE DE TEMAKI CAMARAO EMPA',
        precoCentavos: 5200,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'CLONE DE TEMAKI PEIXE BRANCO',
        precoCentavos: 5200,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'CLONE DE TEMAKI POLVO',
        precoCentavos: 5200,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'CLONE DE TEMAKI SKIN',
        precoCentavos: 3800,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
    ],
  },
  {
    nome: 'Combos',
    produtos: [
      {
        nome: 'COMBINHO',
        precoCentavos: 3500,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'COMBO 1',
        precoCentavos: 4900,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'COMBO 2',
        precoCentavos: 5500,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'COMBO 3',
        precoCentavos: 9100,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'COMPLETAO',
        precoCentavos: 9800,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'COMBO ESPECIAL',
        precoCentavos: 10200,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'PREMIUM DRAGON PORCAO INTEIRA',
        precoCentavos: 16200,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'PREMIUM DRAGON PORCAO MEIA',
        precoCentavos: 8100,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'PREMIUM  FIRE PORCAO INTERIA',
        precoCentavos: 15000,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'PREMIUM  FIRE PORCAO MEIA',
        precoCentavos: 7500,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
    ],
  },
  {
    nome: 'Pecas Especiais',
    produtos: [
      {
        nome: 'EBI JOY 5 UN',
        precoCentavos: 3500,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'JOY EBI 5 UN',
        precoCentavos: 3500,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'JOY JOY 5 UN',
        precoCentavos: 3500,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'FOLHEADO ROOL 5 UN',
        precoCentavos: 3500,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'CARIOCA ESPECIAL 5 UN',
        precoCentavos: 3500,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'KANI QUEIJO FRITO 5 UN',
        precoCentavos: 3500,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'KANI QUEIJO NATURAL 5 UN',
        precoCentavos: 3500,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'EBI CROCK',
        precoCentavos: 4000,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
    ],
  },
  {
    nome: 'Petiscos',
    produtos: [
      {
        nome: 'CAMARAO AO PANKO COM CREAM',
        precoCentavos: 4500,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'BATATA FRITA G',
        precoCentavos: 2700,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'BATATA FRITA P',
        precoCentavos: 1800,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'FILE AO MOLHO MADEIRA COM FRITAS',
        precoCentavos: 4800,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'FILE DE CAMARAO',
        precoCentavos: 5500,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'CAMARAO ALHO E OLEO',
        precoCentavos: 5600,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'CAMARAO EMPANADO',
        precoCentavos: 3800,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'PASTEL DE CAMARAO',
        precoCentavos: 3500,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'PASTEL DE CARNE',
        precoCentavos: 3500,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'PASTEL DE FRANGO',
        precoCentavos: 3500,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'PASTEL DE QUEIJO',
        precoCentavos: 3500,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'PASTEL DE QUEIJO DO REINO',
        precoCentavos: 3900,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'ENTRADINHA DE SALMAO',
        precoCentavos: 800,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'BOLINHO DE BACALHAU',
        precoCentavos: 3300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'BOLINHO DE CHARQUE',
        precoCentavos: 3300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'CARNE DE SOL COM FRITAS',
        precoCentavos: 4000,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'CALABRESA COM FRITAS',
        precoCentavos: 4000,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
    ],
  },
  {
    nome: 'Pratos Quentes',
    produtos: [
      {
        nome: 'CAMARAO AO MOLHO DE TOMATE',
        precoCentavos: 4300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'MINI FRANGO EMPANADO',
        precoCentavos: 2500,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'EXEC FRANGO EMPANADO',
        precoCentavos: 3300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'PORCAO FRANGO EMPANADO',
        precoCentavos: 5000,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'FAMILIA FRANGO EMPANADO',
        precoCentavos: 9800,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'PQ FRANGO A PARMEGIANA',
        precoCentavos: 3200,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'PQ FILE A PARMEGIANA',
        precoCentavos: 3500,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'PQ CAMARAO A PARMEGIANA',
        precoCentavos: 4300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'PQ MEDALHAO DE FILE MIGNON',
        precoCentavos: 3900,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'PQ CAMARAO INTERNACIONAL',
        precoCentavos: 4300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'PQ CAMARAO CROCANTE COM ARROZ CREMOSO',
        precoCentavos: 4300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'PQ CAMARAO AO MOLHOS DE TOMATE',
        precoCentavos: 4300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'INUT8',
        precoCentavos: 5400,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'MINI CARNE COM BATATA IMPERIAL',
        precoCentavos: 2600,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'EXEC CARNE COM BATATA IMPERIAL',
        precoCentavos: 3500,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'PORCAO CARNE COM BATATA IMPERIAL',
        precoCentavos: 5400,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'FAMILIA CARNE COM BATATA IMPERIAL',
        precoCentavos: 10200,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'MINI FRANGO XADREZ',
        precoCentavos: 2700,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'EXEC FRANGO XADREZ',
        precoCentavos: 3500,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'PORCAO FRANGO XADREZ',
        precoCentavos: 5400,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'FAMILIA FRANGO XADREZ',
        precoCentavos: 10200,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'MINI FRANGO A PARMEGIANA',
        precoCentavos: 2700,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'EXEC FRANGO A PARMEGIANA',
        precoCentavos: 3500,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'PORCAO FRANGO A PARMEGIANA',
        precoCentavos: 5400,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'FAMILIA FRANGO A PARMEGIANA',
        precoCentavos: 10200,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'MINI FILE A PARMEGIANA',
        precoCentavos: 3100,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'EXEC FILE A PARMEGIANA',
        precoCentavos: 4000,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'PORCAO FILE A PARMEGIANA',
        precoCentavos: 6100,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'FAMILIA FILE A PARMEGIANA',
        precoCentavos: 12100,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'MINI CARNE ACEBOLADA',
        precoCentavos: 2700,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'EXEC CARNE ACEBOLADA',
        precoCentavos: 3500,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'PORCAO CARNE ACEBOLADA',
        precoCentavos: 5400,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'FAMILIA CARNE ACEBOLADA',
        precoCentavos: 12300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'MINI CAMARAO EMPANADO',
        precoCentavos: 3200,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'EXEC CAMARAO EMPANADO',
        precoCentavos: 4100,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'PORCAO CAMARAO EMPANADO',
        precoCentavos: 6100,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'FAMILIA CAMARAO EMPANADO',
        precoCentavos: 11900,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'INUT17',
        precoCentavos: 2200,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'INUT16',
        precoCentavos: 2900,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'INUT15',
        precoCentavos: 5600,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'INUT14',
        precoCentavos: 7800,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'INUT13',
        precoCentavos: 2200,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'INUT11',
        precoCentavos: 2900,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'INUT10',
        precoCentavos: 5600,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'INUT9',
        precoCentavos: 7800,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'MINI CAMARAO A PARMEGIANA',
        precoCentavos: 3300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'EXEC CAMARAO A PARMEGIANA',
        precoCentavos: 4300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'PORCAO CAMARAO A PARMEGIANA',
        precoCentavos: 6700,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'FAMILIA CAMARAO A PARMEGIANA',
        precoCentavos: 12300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
    ],
  },
  {
    nome: 'Promocao Do Dia',
    produtos: [
      {
        nome: 'RODIZIO + COMPLETO + GUARANA 1L',
        precoCentavos: 7000,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'EXECUTIVO DE CARNE COM BATATA IMPERIAL',
        precoCentavos: 2400,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: '10 PECAS DE SUSHI VARIADAS',
        precoCentavos: 2300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'EXECUTIVO YAKISSOBA TRADICINAL',
        precoCentavos: 2400,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'COMBO 1 + 1 TEMAKI + 10 PECAS VARIADAS',
        precoCentavos: 3300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'EXECUTIVO FRANGO A PARMEGIANA',
        precoCentavos: 2400,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: '10 PECAS DE SUSHI CARIOCA',
        precoCentavos: 2000,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'EXECUTIVO DE BIFUM TRADICIONAL',
        precoCentavos: 2400,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUSHIBURGUER MISTO',
        precoCentavos: 2200,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'EXECUTIVO CARNE ACEBOLADA',
        precoCentavos: 2400,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'PIZZA DELIVERY',
        precoCentavos: 2900,
        fiscalNcm: '19021100',
        fiscalCest: null,
        fiscalCfop: '5101',
        fiscalIcmsCsosn: '202',
        fiscalPisCst: '49',
        fiscalCofinsCst: '49',
      },
      {
        nome: 'MINI POKE',
        precoCentavos: 3100,
        fiscalNcm: '19021100',
        fiscalCest: null,
        fiscalCfop: '5101',
        fiscalIcmsCsosn: '202',
        fiscalPisCst: '49',
        fiscalCofinsCst: '49',
      },
      {
        nome: 'HOT CROCK',
        precoCentavos: 3000,
        fiscalNcm: '19021100',
        fiscalCest: null,
        fiscalCfop: '5101',
        fiscalIcmsCsosn: '202',
        fiscalPisCst: '49',
        fiscalCofinsCst: '49',
      },
      {
        nome: 'COMBO 1 10 PECAS SUSHI 1 TEMAKI',
        precoCentavos: 4300,
        fiscalNcm: '19021100',
        fiscalCest: null,
        fiscalCfop: '5101',
        fiscalIcmsCsosn: '202',
        fiscalPisCst: '49',
        fiscalCofinsCst: '49',
      },
      {
        nome: '5 CARIOCA 5 HOT ROLL',
        precoCentavos: 2800,
        fiscalNcm: '19021100',
        fiscalCest: null,
        fiscalCfop: '5101',
        fiscalIcmsCsosn: '202',
        fiscalPisCst: '49',
        fiscalCofinsCst: '49',
      },
      {
        nome: 'SUSHIBURGUER FRITO',
        precoCentavos: 2800,
        fiscalNcm: '19021100',
        fiscalCest: null,
        fiscalCfop: '5101',
        fiscalIcmsCsosn: '202',
        fiscalPisCst: '49',
        fiscalCofinsCst: '49',
      },
      {
        nome: 'EXECUTIVO FRANGO XADREZ',
        precoCentavos: 2800,
        fiscalNcm: '19021100',
        fiscalCest: null,
        fiscalCfop: '5101',
        fiscalIcmsCsosn: '202',
        fiscalPisCst: '49',
        fiscalCofinsCst: '49',
      },
      {
        nome: 'EXECUTIVO DE YAKISOBA TRADICIONAL',
        precoCentavos: 2800,
        fiscalNcm: '19021100',
        fiscalCest: null,
        fiscalCfop: '5101',
        fiscalIcmsCsosn: '202',
        fiscalPisCst: '49',
        fiscalCofinsCst: '49',
      },
    ],
  },
  {
    nome: 'Rdz A La Cart',
    produtos: [
      {
        nome: 'RDZ ARCO IRIS',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ CARIOCA DE SALMAO',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ CANAPE DE CAMARAO',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ HOSSOMAKI DE CAMARAO',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ CANAPE DE KANI C CAMARAO',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ CANAPE DE KANI C PASTA SALMAO',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ CANAPE DE KANI',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ HOSSOMAKI DE SALMAO C CEBOLINHA',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ CANAPE DE PEIXE BRANCO',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ CANAPE DE SALMAO',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ CANAPE FRITO KANI',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ HOT ROLL',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ CANAPE FRITO C PASTA KANI',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ CANAPE FRITO DE PASTA DE SALMAO',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ CANAPE FRITO DE PASTA DE KANI',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ NIGUIRI DE KANI FRITO',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ COCADINHA DE KANI',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ NIGUIRI DE PEIXE BRANCO MACARICADO',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ NIGUIRI DE KANI',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ URAMAKI DE CAMARAO',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ URAMAKI DE KANI',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ URAMAKI DE SALMAO CREAM C E CEBOLINHA',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ URAMAKI DE SALMAO',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ ESTRELINHA DE PEIXE BRANCO C CEBO',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ ESTRELINHA DE SALMAO',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ SUITE RAQUEL',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
    ],
  },
  {
    nome: 'Rdz Pecas Especiais',
    produtos: [
      {
        nome: 'RDZ EBI JOY',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ JOY EBI',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ JOY JOY',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ FOLHEADO ROOL',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ CARIOCA ESPECIAL',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ KANI QUEIJO FRITO',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ KANI QUEIJO NATURAL',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
    ],
  },
  {
    nome: 'Rdz Pratos',
    produtos: [
      {
        nome: 'RDZ YAKISOBA P',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ BIFUM P',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
    ],
  },
  {
    nome: 'Rdz Rolinho',
    produtos: [
      {
        nome: 'RDZ ROLINHO PRIMAVERA',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ ROLINHO CAMARAO',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ ROLINHO SALMAO',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ ROLINHO QUEIJO',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ ROMEU E JULIETA',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
    ],
  },
  {
    nome: 'Rdz Sunomono',
    produtos: [
      {
        nome: 'RDZ SUNOMONO P SALMAO',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ SUNOMONO P PEIXE BRANCO',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ SUNOMONO P POLVO',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ SUNOMONO P KANI',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ SUNOMONO P MISTO',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ SUNOMONO P CAMARAO',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ SUNOMO P PEPINO',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
    ],
  },
  {
    nome: 'Rdz Temaki',
    produtos: [
      {
        nome: 'RDZ TEMAKI SALMAO',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ TEMAKI CAMARAO EMPANADO',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ TEMAKI KANI',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ TEMAKI CALIFORNIA',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ TEMAKI PEIXE BRANCO',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ TEMAKI SKIN',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ TEMAKI MISTO',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ TEMAKI PASTA DE SALMAO',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ TEMAKI PASTA DE KANI',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RDZ TEMAKI PASTA DE PEIXE BRANCO',
        precoCentavos: 0,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
    ],
  },
  {
    nome: 'Rodizio',
    produtos: [
      {
        nome: 'RODIZIO',
        precoCentavos: 8000,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'RODIZIO II',
        precoCentavos: 8500,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'MEIO RODIZIO',
        precoCentavos: 4000,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
    ],
  },
  {
    nome: 'Rolinhos',
    produtos: [
      {
        nome: 'ROLINHO PRIMAVERA',
        precoCentavos: 1200,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'ROLINHO CAMARAO',
        precoCentavos: 1300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'ROLINHO SALMAO',
        precoCentavos: 1700,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'ROLINHO QUEIJO',
        precoCentavos: 1200,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'ROLINHO ROMEU E JULIETA',
        precoCentavos: 1100,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
    ],
  },
  {
    nome: 'Sashimi',
    produtos: [
      {
        nome: 'SASHIMI SALMAO',
        precoCentavos: 4000,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SASHIMI PEIXE BRANCO',
        precoCentavos: 3000,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
    ],
  },
  {
    nome: 'Sobremesa',
    produtos: [
      {
        nome: 'BROWNIE COM SORVETE',
        precoCentavos: 2200,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: '1 BOLA DE SORVETE',
        precoCentavos: 700,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: '2 BOLA DE SORVETE',
        precoCentavos: 900,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
    ],
  },
  {
    nome: 'Sunomono',
    produtos: [
      {
        nome: 'SUNOMONO P SALMAO',
        precoCentavos: 4400,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUNOMONO G SALMAO',
        precoCentavos: 7600,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUNOMONO P PEIXE BRANCO',
        precoCentavos: 3900,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUNOMONO G PEIXE BRANCO',
        precoCentavos: 7200,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUNOMONO P POLVO',
        precoCentavos: 3900,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUNOMONO G POLVO',
        precoCentavos: 7200,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUNOMONO P KANI',
        precoCentavos: 2900,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUNOMONO G KANI',
        precoCentavos: 5100,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUNOMONO P MISTO',
        precoCentavos: 4400,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUNOMONO G MISTO',
        precoCentavos: 7600,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUNOMONO P CAMARAO',
        precoCentavos: 4400,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUNOMONO G CAMARAO',
        precoCentavos: 7600,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUNOMO P PEPINO',
        precoCentavos: 2200,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUNOMONO G PEPINO',
        precoCentavos: 3400,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'MINI POKE MISTO',
        precoCentavos: 3700,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'MINI CAMARÃO CROCK',
        precoCentavos: 2500,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
    ],
  },
  {
    nome: 'Supremo',
    produtos: [
      {
        nome: 'SUPREMO BABY MISTO',
        precoCentavos: 4600,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'MINI SUPREMO SALMAO',
        precoCentavos: 5700,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'MINI SUPREMO CAMARAO',
        precoCentavos: 5700,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUPER SUPREMO SALMAO',
        precoCentavos: 10400,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUPER SUPREMO CAMARAO',
        precoCentavos: 10400,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUPER MISTO',
        precoCentavos: 10400,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
    ],
  },
  {
    nome: 'Sushiburguer',
    produtos: [
      {
        nome: 'SUSHIBURGUER SALMAO',
        precoCentavos: 3500,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUSHIBURGUER CAMARAO',
        precoCentavos: 3500,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'SUSHIBURGUER KANI',
        precoCentavos: 3500,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'HOT CROCK MISTO',
        precoCentavos: 3600,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
    ],
  },
  {
    nome: 'Temakis',
    produtos: [
      {
        nome: 'TEMAKI SALMAO NATURAL',
        precoCentavos: 3400,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'TEMAKI SALMAO FRITO',
        precoCentavos: 3700,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'TEMAKI CAMARAO EMPAN NATURAL',
        precoCentavos: 3400,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'TEMAKI CAMARAO EMPAN FRITO',
        precoCentavos: 3700,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'TEMAKI KANI NATURAL',
        precoCentavos: 3400,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'TEMAKI KANI FRITO',
        precoCentavos: 3700,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'TEMAKI CALIFORNIA NATURAL',
        precoCentavos: 2500,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'TEMAKI CALIFORNIA FRITO',
        precoCentavos: 2900,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'TEMAKI PEIXE BRANCO NATURAL',
        precoCentavos: 3400,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'TEMAKI PEIXE BRANCO FRITO',
        precoCentavos: 3700,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'TEMAKI SKIN NATURAL',
        precoCentavos: 2500,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'TEMAKI SKIN FRITO',
        precoCentavos: 2900,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'TEMAKI MISTO NATURAL',
        precoCentavos: 3400,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'TEMAKI MISTO FRITO',
        precoCentavos: 3700,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'TEMAKI PASTA DE SALMAO NATURAL',
        precoCentavos: 3400,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'TEMAKI PASTA DE SALMAO FRITO',
        precoCentavos: 3700,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'TEMAKI PASTA DE KANI NATURAL',
        precoCentavos: 3400,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'TEMAKI PASTA DE KANI FRITO',
        precoCentavos: 3700,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'TEMAKI PASTA DE PEIXE BRAN NATURAL',
        precoCentavos: 3400,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'TEMAKI PASTA DE PEIXE BRAN FRITO',
        precoCentavos: 3700,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'TEMAKI PASTA DE SKIN NATURAL',
        precoCentavos: 2500,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'TEMAKI PASTA DE SKIN FRITO',
        precoCentavos: 2900,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'TEMAKI CAMARAO FRITO NATURAL',
        precoCentavos: 3400,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'TEMAKI CAMARAO FRITO FRITO',
        precoCentavos: 3700,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'TEMAKI ROMEU E JULIETA FRITO',
        precoCentavos: 3700,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'TEMAKI SEM ARROZ NATURAL',
        precoCentavos: 4600,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'TEMAKI SEM ARROZ FRITO',
        precoCentavos: 4700,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'TEMAKI CAMARAO PRE COZIDO',
        precoCentavos: 3700,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
    ],
  },
  {
    nome: 'Yakissoba',
    produtos: [
      {
        nome: 'MINI YAKISSOBA TRADICIONAL',
        precoCentavos: 2800,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'EXEC YAKISSOBA TRADICIONAL',
        precoCentavos: 3300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'PORCAO YAKISSOBA TRADIONAL',
        precoCentavos: 5900,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'FAMILIA YAKISSOBA TRADICIONAL',
        precoCentavos: 9600,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'EXEC YAKISSOBA ESPECIAL',
        precoCentavos: 4100,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'PORCAO YAKISSOBA ESPECIAL',
        precoCentavos: 6300,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'FAMILIA YAKISSOBA ESPECIAL',
        precoCentavos: 11100,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'EXEC YAKISSOBA SO CAMARAO',
        precoCentavos: 4600,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'PORCAO YAKISSOBA SO CAMARAO',
        precoCentavos: 7600,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
      {
        nome: 'FAMILIA YAKISSOBA SO CAMARAO',
        precoCentavos: 13000,
        fiscalNcm: '21069090',
        fiscalCest: null,
        fiscalCfop: '5102',
        fiscalIcmsCsosn: '102',
        fiscalPisCst: '07',
        fiscalCofinsCst: '07',
      },
    ],
  },
]

export const TOTAL_PRODUTOS_CHINA_EXPRESS = 369
export const TOTAL_CATEGORIAS_CHINA_EXPRESS = 30
