export const CODIGOS_ERRO_DIVISAO_CONTA = {
  ENTRADA_INVALIDA: 'ENTRADA_INVALIDA',
  CAIXA_NAO_ABERTO: 'CAIXA_NAO_ABERTO',
  PEDIDO_NAO_ENCONTRADO: 'PEDIDO_NAO_ENCONTRADO',
  PEDIDO_NAO_ABERTO: 'PEDIDO_NAO_ABERTO',
  DIVISAO_NAO_ENCONTRADA: 'DIVISAO_NAO_ENCONTRADA',
  DIVISAO_JA_EXISTE: 'DIVISAO_JA_EXISTE',
  DIVISAO_NAO_ESTA_ATIVA: 'DIVISAO_NAO_ESTA_ATIVA',
  DIVISAO_NAO_PERMITIDA_COM_PAGAMENTOS_EXISTENTES:
    'DIVISAO_NAO_PERMITIDA_COM_PAGAMENTOS_EXISTENTES',
  DIVISAO_PRECISA_DE_DUAS_OU_MAIS_PARTES: 'DIVISAO_PRECISA_DE_DUAS_OU_MAIS_PARTES',
  DIVISAO_VALOR_PARTE_INVALIDO: 'DIVISAO_VALOR_PARTE_INVALIDO',
  DIVISAO_VALORES_NAO_FECHAM_COM_TOTAL_PEDIDO:
    'DIVISAO_VALORES_NAO_FECHAM_COM_TOTAL_PEDIDO',
  PARTE_DIVISAO_NAO_ENCONTRADA: 'PARTE_DIVISAO_NAO_ENCONTRADA',
  PARTE_NAO_PERTENCE_A_DIVISAO: 'PARTE_NAO_PERTENCE_A_DIVISAO',
  PARTE_JA_ESTA_QUITADA: 'PARTE_JA_ESTA_QUITADA',
  PAGAMENTO_EXCEDE_VALOR_RESTANTE_DA_PARTE: 'PAGAMENTO_EXCEDE_VALOR_RESTANTE_DA_PARTE',
  PAGAMENTO_EXCEDE_VALOR_RESTANTE_DO_PEDIDO: 'PAGAMENTO_EXCEDE_VALOR_RESTANTE_DO_PEDIDO',
  ALTERACAO_PEDIDO_BLOQUEADA_POR_DIVISAO_ATIVA:
    'ALTERACAO_PEDIDO_BLOQUEADA_POR_DIVISAO_ATIVA',
  CANCELAMENTO_DIVISAO_NAO_PERMITIDO_COM_PAGAMENTOS:
    'CANCELAMENTO_DIVISAO_NAO_PERMITIDO_COM_PAGAMENTOS',
  FINALIZACAO_BLOQUEADA_POR_PARTES_PENDENTES:
    'FINALIZACAO_BLOQUEADA_POR_PARTES_PENDENTES',
  PEDIDO_TOTAL_INVALIDO: 'PEDIDO_TOTAL_INVALIDO',
} as const

export type CodigoErroDivisaoConta =
  (typeof CODIGOS_ERRO_DIVISAO_CONTA)[keyof typeof CODIGOS_ERRO_DIVISAO_CONTA]

export class ErroDivisaoConta extends Error {
  readonly codigo: CodigoErroDivisaoConta

  constructor(codigo: CodigoErroDivisaoConta, mensagem: string) {
    super(mensagem)
    this.name = 'ErroDivisaoConta'
    this.codigo = codigo
  }
}
