export const CODIGOS_ERRO_PIZZAS = {
  PIZZA_CATEGORIA_NAO_ENCONTRADA: 'PIZZA_CATEGORIA_NAO_ENCONTRADA',
  PIZZA_CATEGORIA_INATIVA: 'PIZZA_CATEGORIA_INATIVA',
  PIZZA_TAMANHO_NAO_ENCONTRADO: 'PIZZA_TAMANHO_NAO_ENCONTRADO',
  PIZZA_TAMANHO_INATIVO: 'PIZZA_TAMANHO_INATIVO',
  PIZZA_SABOR_NAO_ENCONTRADO: 'PIZZA_SABOR_NAO_ENCONTRADO',
  PIZZA_SABOR_INATIVO: 'PIZZA_SABOR_INATIVO',
  PIZZA_SABOR_NAO_PERTENCE_A_CATEGORIA: 'PIZZA_SABOR_NAO_PERTENCE_A_CATEGORIA',
  PIZZA_SABOR_DUPLICADO: 'PIZZA_SABOR_DUPLICADO',
  PIZZA_SEM_SABOR: 'PIZZA_SEM_SABOR',
  PIZZA_QUANTIDADE_SABORES_EXCEDE_LIMITE: 'PIZZA_QUANTIDADE_SABORES_EXCEDE_LIMITE',
  PIZZA_PRECO_NAO_CONFIGURADO_PARA_TAMANHO: 'PIZZA_PRECO_NAO_CONFIGURADO_PARA_TAMANHO',
  PIZZA_REGRA_PRECIFICACAO_INVALIDA: 'PIZZA_REGRA_PRECIFICACAO_INVALIDA',
  ALTERACAO_PIZZA_BLOQUEADA_POR_DIVISAO_ATIVA:
    'ALTERACAO_PIZZA_BLOQUEADA_POR_DIVISAO_ATIVA',
  ENTRADA_INVALIDA: 'ENTRADA_INVALIDA',
  NOME_OBRIGATORIO: 'NOME_OBRIGATORIO',
  MAXIMO_SABORES_INVALIDO: 'MAXIMO_SABORES_INVALIDO',
  PRECO_INVALIDO: 'PRECO_INVALIDO',
  QUANTIDADE_PIZZA_NAO_ALTERAVEL: 'QUANTIDADE_PIZZA_NAO_ALTERAVEL',
  SEM_PERMISSAO: 'SEM_PERMISSAO',
} as const

export type CodigoErroPizzas =
  (typeof CODIGOS_ERRO_PIZZAS)[keyof typeof CODIGOS_ERRO_PIZZAS]

export class ErroPizzas extends Error {
  readonly codigo: CodigoErroPizzas

  constructor(codigo: CodigoErroPizzas, mensagem: string) {
    super(mensagem)
    this.name = 'ErroPizzas'
    this.codigo = codigo
  }
}
