export const ACAO_AUDITORIA = {
  LOGIN: 'LOGIN',
  OPERADOR_SALVAR: 'OPERADOR_SALVAR',
  CAIXA_ABRIR: 'CAIXA_ABRIR',
  CAIXA_FECHAR: 'CAIXA_FECHAR',
  CAIXA_MOVIMENTO: 'CAIXA_MOVIMENTO',
  PEDIDO_CRIAR: 'PEDIDO_CRIAR',
  PEDIDO_CANCELAR: 'PEDIDO_CANCELAR',
  ITEM_CANCELAR: 'ITEM_CANCELAR',
  DESCONTO: 'DESCONTO',
  PAGAMENTO: 'PAGAMENTO',
  MESA_TRANSFERIR: 'MESA_TRANSFERIR',
  CATALOGO: 'CATALOGO',
} as const

export type AcaoAuditoria = (typeof ACAO_AUDITORIA)[keyof typeof ACAO_AUDITORIA]

export const ORIGEM_AUDITORIA = {
  PDV: 'PDV',
  DASHBOARD: 'DASHBOARD',
} as const

export type OrigemAuditoria = (typeof ORIGEM_AUDITORIA)[keyof typeof ORIGEM_AUDITORIA]
