export const CODIGOS_ERRO_DELIVERY = {
  ENTREGA_NAO_ENCONTRADA: 'ENTREGA_NAO_ENCONTRADA',
  PEDIDO_NAO_E_DELIVERY: 'PEDIDO_NAO_E_DELIVERY',
  TAXA_ENTREGA_INVALIDA: 'TAXA_ENTREGA_INVALIDA',
  STATUS_ENTREGA_INVALIDO: 'STATUS_ENTREGA_INVALIDO',
  TRANSICAO_STATUS_ENTREGA_INVALIDA: 'TRANSICAO_STATUS_ENTREGA_INVALIDA',
  DADOS_ENDERECO_INVALIDOS: 'DADOS_ENDERECO_INVALIDOS',
  TOTAL_MENOR_QUE_VALOR_JA_QUITADO: 'TOTAL_MENOR_QUE_VALOR_JA_QUITADO',
  PEDIDO_NAO_ABERTO: 'PEDIDO_NAO_ABERTO',
  PEDIDO_NAO_ENCONTRADO: 'PEDIDO_NAO_ENCONTRADO',
  CAIXA_NAO_ABERTO: 'CAIXA_NAO_ABERTO',
  ENTRADA_INVALIDA: 'ENTRADA_INVALIDA',
} as const

export type CodigoErroDelivery =
  (typeof CODIGOS_ERRO_DELIVERY)[keyof typeof CODIGOS_ERRO_DELIVERY]

export class ErroDelivery extends Error {
  readonly codigo: CodigoErroDelivery

  constructor(codigo: CodigoErroDelivery, mensagem: string) {
    super(mensagem)
    this.name = 'ErroDelivery'
    this.codigo = codigo
  }
}
