export const CODIGOS_ERRO_MESAS = {
  NUMERO_OBRIGATORIO: 'NUMERO_OBRIGATORIO',
  INTERVALO_INVALIDO: 'INTERVALO_INVALIDO',
  MESA_NAO_ENCONTRADA: 'MESA_NAO_ENCONTRADA',
  ENTRADA_INVALIDA: 'ENTRADA_INVALIDA',
  PEDIDO_NAO_ENCONTRADO: 'PEDIDO_NAO_ENCONTRADO',
  PEDIDO_NAO_E_DE_MESA: 'PEDIDO_NAO_E_DE_MESA',
  PEDIDO_NAO_ESTA_ABERTO: 'PEDIDO_NAO_ESTA_ABERTO',
  MESA_DESTINO_IGUAL_ORIGEM: 'MESA_DESTINO_IGUAL_ORIGEM',
  MESA_DESTINO_NAO_ESTA_LIVRE: 'MESA_DESTINO_NAO_ESTA_LIVRE',
  MESA_DESTINO_INATIVA: 'MESA_DESTINO_INATIVA',
  MESA_POSSUI_PEDIDO_ABERTO: 'MESA_POSSUI_PEDIDO_ABERTO',
  MESA_JA_PERTENCE_A_AGRUPAMENTO: 'MESA_JA_PERTENCE_A_AGRUPAMENTO',
  PEDIDO_JA_POSSUI_AGRUPAMENTO: 'PEDIDO_JA_POSSUI_AGRUPAMENTO',
  AGRUPAMENTO_NAO_ENCONTRADO: 'AGRUPAMENTO_NAO_ENCONTRADO',
  AGRUPAMENTO_NAO_ESTA_ATIVO: 'AGRUPAMENTO_NAO_ESTA_ATIVO',
  QUANTIDADE_MESAS_AGRUPAMENTO_INVALIDA: 'QUANTIDADE_MESAS_AGRUPAMENTO_INVALIDA',
  MESA_PRINCIPAL_NAO_INFORMADA: 'MESA_PRINCIPAL_NAO_INFORMADA',
  MESCLAGEM_DE_PEDIDOS_NAO_SUPORTADA: 'MESCLAGEM_DE_PEDIDOS_NAO_SUPORTADA',
  TRANSFERENCIA_DE_PEDIDO_AGRUPADO_NAO_SUPORTADA:
    'TRANSFERENCIA_DE_PEDIDO_AGRUPADO_NAO_SUPORTADA',
  CAIXA_NAO_ABERTO: 'CAIXA_NAO_ABERTO',
  MESA_ORIGEM_NAO_OCUPADA: 'MESA_ORIGEM_NAO_OCUPADA',
} as const

export type CodigoErroMesas = (typeof CODIGOS_ERRO_MESAS)[keyof typeof CODIGOS_ERRO_MESAS]

export class ErroMesas extends Error {
  readonly codigo: CodigoErroMesas

  constructor(codigo: CodigoErroMesas, mensagem: string) {
    super(mensagem)
    this.name = 'ErroMesas'
    this.codigo = codigo
  }
}
